# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobile-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-tvOS


end
